### ISSUE TITLE
ERR_TOO_MANY_REDIRECTS when deployed on Heroku and connected to Cloudflare

### ISSUE THREAD

**Issue by mqsley** [ryanckulp/speedrail#122]
Following the 24 hour MVP setup I get the error
ERR_TOO_MANY_REDIRECTS

When I comment out  "config.force_ssl = true" on config/environments/production then the site shows up properly but no logins or sign up actions worked as the requests flag security

**Comment by niklasbabel** [comment]
maybe set SSL to "Full" on Cloudflare - no problems on my end with Cloudflare + speedrails
