### ISSUE TITLE
User Who Hasn't Finished Onboarding Cannot Subscribe

### ISSUE THREAD

**Issue by stets** [ryanckulp/speedrail#63]
I found a bug for users who haven't started a trial or where `user.finished_onboarding? == false` who try to subscribe from the My Account page

## Steps to Replicate

- Sign Up, get redirected to `/subscribe` route
- Do not start the trial, instead click Account or navigate to `/account` route
- Click Manage

The browser hangs on this screen:

![image](https://user-images.githubusercontent.com/2044547/208433947-75ab5916-c61a-46e9-b062-1e5207e16753.png)

## Notes:

I believe this has something to do with unsafe URLs, but [billing_portal_controller.rb](https://github.com/ryanckulp/speedrail/blob/3c51d9323616a66af477ea97bf4641b310ff49bc/app/controllers/billing_portal_controller.rb#L9) has `allow_other_host: true` set, so it should work.

However, after clicking Manage, the stripe checkout URL is cut off after the `#` "hashtag character". Grabbing the real session URL from console and navigating directly to it works fine and loads the checkout. 

Session URL has a format like:

`https://checkout.stripe.com/c/pay/cs_test_<long_string_of_characters>#<another_long_string>`

I tried using `gsub` on the `session.url` to substitute the `#` hash sign with `%23` URL encoding, but that didn't work either. 

Happy to open a PR if I know what the cause of this is

**Comment by mrandrewjbaker** [comment]
Can you verify that users who have `user.finished_onboarding? == true` are able to view this, and not specific to unfinished users? I don’t believe `#` and ‘%23` are the issue. 🤔

**Comment by stets** [comment]
I'm thinking this behavior may be intended -- looks like the `billing_portal` route should only be requested with a `POST` not a GET like is happening when the user skips the onboarding flow. Maybe the manage button could be reworked as a form only if the user's onboarding status is false

**Comment by ryanckulp** [comment]
@stets thanks for diggin!

* everyone should be able to view Account page, in case they want to update their email/password
* clicking `/billing_portal` link on account page should simply create a Checkout session vs BillingPortal session
* the creation of a Checkout vs billing is handled by `finished_onboarding?` which will always be false if they have not done a successful Checkout ([source](https://github.com/ryanckulp/speedrail/blob/master/app/models/concerns/onboardable.rb#L8))

**Comment by stets** [comment]
Thanks @ryanckulp  -- that all makes sense

- `clicking /billing_portal link on account page should simply create a Checkout session vs BillingPortal session`
This step is where I'm observing the behavior where things break. 

That user who is has not finished onboarding, hits the begin_subscription function, which should redirect them to `session.url`, however the back half of that URL is getting chopped off and stripe will just get hung up

**Comment by ryanckulp** [comment]
@stets after further review, i think the page hangs because you don't yet have a subscription "set," which should be happening in a background job.

drop the `delay` inside `user.delay.set_stripe_subscription`, run back through onboarding (sign up, create subscription) and verify if that fixes things. i may need to tweak how the background jobs boot up.

**Comment by stets** [comment]
> drop the `delay` inside `user.delay.set_stripe_subscription`, run back through onboarding (sign up, create subscription) and verify if that fixes things. I may need to tweak how the background jobs boot up.

Hmm, I gave that a try but still no luck. With `delay` and removing `delay` from that func, I get the same results. The user is getting created and assigned a stripe customer id.

I think this has to due with some weirdness in with redirects and handling that `billing_portal` route. Maybe it is because we are GETing it from the Account Page (breaks) but POSTing to it from the `/subscribe` page 🤔

**Comment by ryanckulp** [comment]
the routes file handles both GET and POST so thats fine. but page will hang when there is no attached customer id when the portal opens. can you confirm there is a customer id?

further you’ll need to just click “save changes” inside the Stripe UI > portal settings, kinda strange. this must be done 1x before it works, but your rails server should tell you that in the browser on localhost.

**Comment by ryanckulp** [comment]
closing this as i believe it was handled recently by https://github.com/ryanckulp/speedrail/commit/e21ea853782214fb5179b58e4c8defcc668b93d1 and what i stated previously about clicking "Save" inside Stripe's UI (very dumb i know).
