### ISSUE TITLE
Suggestion: Add confirm_token logic

### ISSUE THREAD

**Issue by stets** [ryanckulp/speedrail#65]
hey @ryanckulp, I'm starting a new project with this template and I think it'd be nice if speedrail had the confirm token logic to confirm users' emails from the founder hacker course. 

What do you think? 

happy to open a PR for it

**Comment by ryanckulp** [comment]
Devise "[confirmable](https://github.com/heartcombo/devise/blob/main/lib/devise/models/confirmable.rb)" offers this feature out of the box. give it a try by uncommenting `:confirmable` [here](https://github.com/ryanckulp/speedrail/blob/master/app/models/concerns/signupable.rb#L6).

**Comment by stets** [comment]
> Devise "[confirmable](https://github.com/heartcombo/devise/blob/main/lib/devise/models/confirmable.rb)" offers this feature out of the box. give it a try by uncommenting `:confirmable` [here](https://github.com/ryanckulp/speedrail/blob/master/app/models/concerns/signupable.rb#L6).

nice! sgtm
